### ISSUE TITLE
No access to push branch to orgin

### ISSUE THREAD

**Issue by AshleyYangSZ** [PxlBuzzard/IbizaWebExtension#3]
Hi Repo owner,

When I try to push local branch to orgin, get this error, could you assign me access to this repo? I hope to update to support a new extension here.
remote: Permission to PxlBuzzard/IbizaWebExtension.git denied to AshleyYangSZ.
fatal: unable to access 'https://github.com/PxlBuzzard/IbizaWebExtension.git/': The requested URL returned error: 403

**Comment by PxlBuzzard** [comment]
Hey @AshleyYangSZ! I'm happy to let you open Pull Requests and merge changes in here if you'd like. I wouldn't allow direct push access on any repo, but I'm happy to accept any changes you make.

**Comment by AshleyYangSZ** [comment]
Hi @Daniel ***@***.***>,

I didn't intent to push change directly, I wanted to push my feature branch to that repo then create PR based on that, but failed with 401.
So, I forked the repo to my github account and based on that created a PR Support CPC extension by AshleyYangSZ * Pull Request #4 * PxlBuzzard/IbizaWebExtension (github.com)<https://github.com/PxlBuzzard/IbizaWebExtension/pull/4> but it shows in your original repo, a little wired but finally I created PR successfully.
Could you help review it?

Thanks,
Ashley
